# Generated by Django 4.2.20 on 2025-03-21 09:56

import apps.accounts.models.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'blank': 'Tài khoản không được bỏ trống', 'invalid': 'Tài khoản không hợp lệ', 'max_length': 'Tài khoản không thể dài hơn 150 ký tự', 'null': 'Tài khoản không được bỏ trống', 'required': 'Tài khoản không được bỏ trống', 'unique': 'Tài khoản đã tồn tại trên hệ thống'}, max_length=150, unique=True, verbose_name='Tài khoản')),
                ('password', models.CharField(error_messages={'blank': 'Mật khẩu không được bỏ trống', 'invalid': 'Mật khẩu không hợp lệ', 'max_length': 'Mật khẩu không thể dài hơn 128 ký tự', 'null': 'Mật khẩu không được bỏ trống', 'required': 'Mật khẩu không được bỏ trống', 'unique': 'Mật khẩu đã tồn tại trên hệ thống'}, max_length=128, verbose_name='Mật khẩu')),
                ('full_name', models.CharField(error_messages={'blank': 'Họ và tên không được bỏ trống', 'invalid': 'Họ và tên không hợp lệ', 'max_length': 'Họ và tên không thể dài hơn 255 ký tự', 'null': 'Họ và tên không được bỏ trống', 'required': 'Họ và tên không được bỏ trống', 'unique': 'Họ và tên đã tồn tại trên hệ thống'}, max_length=255, verbose_name='Họ và Tên')),
            ],
            options={
                'verbose_name': 'Tài khoản quản trị hệ thống',
                'verbose_name_plural': 'Tài khoản quản trị hệ thống',
                'db_table': 'accounts_admin_user',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian cập nhật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xóa')),
                ('phone_number', models.CharField(error_messages={'blank': 'Số điện thoại không được bỏ trống', 'invalid': 'Số điện thoại không hợp lệ', 'max_length': 'Số điện thoại không thể dài hơn 255 ký tự', 'null': 'Số điện thoại không được bỏ trống', 'required': 'Số điện thoại không được bỏ trống', 'unique': 'Số điện thoại đã tồn tại trên hệ thống'}, max_length=255, unique=True, validators=[apps.accounts.models.utils.validators.validate_phone_number], verbose_name='Số điện thoại')),
                ('password', models.CharField(blank=True, error_messages={'blank': 'Mật khẩu không được bỏ trống', 'invalid': 'Mật khẩu không hợp lệ', 'max_length': 'Mật khẩu không thể dài hơn 255 ký tự', 'null': 'Mật khẩu không được bỏ trống', 'required': 'Mật khẩu không được bỏ trống', 'unique': 'Mật khẩu đã tồn tại trên hệ thống'}, max_length=255, null=True, verbose_name='Mật khẩu')),
                ('code', models.CharField(blank=True, error_messages={'blank': 'Mã người dùng không được bỏ trống', 'invalid': 'Mã người dùng không hợp lệ', 'max_length': 'Mã người dùng không thể dài hơn 100 ký tự', 'null': 'Mã người dùng không được bỏ trống', 'required': 'Mã người dùng không được bỏ trống', 'unique': 'Mã người dùng đã tồn tại trên hệ thống'}, max_length=100, null=True, verbose_name='Mã người dùng')),
                ('full_name', models.CharField(error_messages={'blank': 'Tên người dùng không được bỏ trống', 'invalid': 'Tên người dùng không hợp lệ', 'max_length': 'Tên người dùng không thể dài hơn 255 ký tự', 'null': 'Tên người dùng không được bỏ trống', 'required': 'Tên người dùng không được bỏ trống', 'unique': 'Tên người dùng đã tồn tại trên hệ thống'}, max_length=255, verbose_name='Tên người dùng')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], error_messages={'blank': 'Giới tính không được bỏ trống', 'invalid': 'Giới tính không hợp lệ', 'null': 'Giới tính không được bỏ trống', 'required': 'Giới tính không được bỏ trống'}, max_length=20, null=True, verbose_name='Giới tính')),
                ('email', models.EmailField(blank=True, error_messages={'blank': 'Địa chỉ email không được bỏ trống', 'invalid': 'Địa chỉ email không hợp lệ', 'max_length': 'Địa chỉ email không thể dài hơn 255 ký tự', 'null': 'Địa chỉ email không được bỏ trống', 'required': 'Địa chỉ email không được bỏ trống', 'unique': 'Địa chỉ email đã tồn tại trên hệ thống'}, max_length=255, null=True, verbose_name='Địa chỉ email')),
                ('date_of_birth', models.DateField(blank=True, error_messages={'invalid': 'Ngày sinh không hợp lệ', 'null': 'Ngày sinh không được bỏ trống', 'required': 'Ngày sinh không được bỏ trống'}, null=True, verbose_name='Ngày sinh')),
                ('type', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Nhân viên'), ('MANAGER', 'Quản lý'), ('PHARMACY', 'Nhà thuốc'), ('SUPPLIER', 'Nhà cung cấp'), ('PARTNER', 'Đối tác'), ('SELLER', 'Bán hàng'), ('DOCTOR', 'Bác sĩ')], error_messages={'blank': 'Đối tượng người dùng không được bỏ trống', 'invalid': 'Đối tượng người dùng không hợp lệ', 'null': 'Đối tượng người dùng không được bỏ trống', 'required': 'Đối tượng người dùng không được bỏ trống'}, max_length=100, verbose_name='Đối tượng người dùng')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Đang hoạt động'), ('NOT_ACTIVATED', 'Chưa kích hoạt'), ('LOCKED', 'Vô hiệu hóa')], default='ACTIVATED', error_messages={'blank': 'Trạng thái người dùng không được bỏ trống', 'invalid': 'Trạng thái người dùng không hợp lệ', 'null': 'Trạng thái người dùng không được bỏ trống', 'required': 'Trạng thái người dùng không được bỏ trống'}, max_length=100, verbose_name='Trạng thái người dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_by', to='accounts.user', verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_deleted_by', to='accounts.user', verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_by', to='accounts.user', verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Tài khoản người dùng',
                'verbose_name_plural': 'Tài khoản người dùng',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian cập nhật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xóa')),
                ('phone_number', models.CharField(error_messages={'blank': 'Số điện thoại không được bỏ trống', 'invalid': 'Số điện thoại không hợp lệ', 'max_length': 'Số điện thoại không thể dài hơn 255 ký tự', 'null': 'Số điện thoại không được bỏ trống', 'required': 'Số điện thoại không được bỏ trống', 'unique': 'Số điện thoại đã tồn tại trên hệ thống'}, max_length=255, unique=True, validators=[apps.accounts.models.utils.validators.validate_phone_number], verbose_name='Số điện thoại')),
                ('password', models.CharField(blank=True, error_messages={'blank': 'Mật khẩu không được bỏ trống', 'invalid': 'Mật khẩu không hợp lệ', 'max_length': 'Mật khẩu không thể dài hơn 255 ký tự', 'null': 'Mật khẩu không được bỏ trống', 'required': 'Mật khẩu không được bỏ trống', 'unique': 'Mật khẩu đã tồn tại trên hệ thống'}, max_length=255, null=True, verbose_name='Mật khẩu')),
                ('code', models.CharField(blank=True, error_messages={'blank': 'Mã khách hàng không được bỏ trống', 'invalid': 'Mã khách hàng không hợp lệ', 'max_length': 'Mã khách hàng không thể dài hơn 20 ký tự', 'null': 'Mã khách hàng không được bỏ trống', 'required': 'Mã khách hàng không được bỏ trống', 'unique': 'Mã khách hàng đã tồn tại trên hệ thống'}, max_length=100, null=True, verbose_name='Mã khách hàng')),
                ('full_name', models.CharField(error_messages={'blank': 'Tên khách hàng không được bỏ trống', 'invalid': 'Tên khách hàng không hợp lệ', 'max_length': 'Tên khách hàng không thể dài hơn 255 ký tự', 'null': 'Tên khách hàng không được bỏ trống', 'required': 'Tên khách hàng không được bỏ trống', 'unique': 'Tên khách hàng đã tồn tại trên hệ thống'}, max_length=255, verbose_name='Tên khách hàng')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], error_messages={'blank': 'Giới tính không được bỏ trống', 'invalid': 'Giới tính không hợp lệ', 'null': 'Giới tính không được bỏ trống', 'required': 'Giới tính không được bỏ trống'}, max_length=20, null=True, verbose_name='Giới tính')),
                ('email', models.EmailField(blank=True, error_messages={'blank': 'Địa chỉ email không được bỏ trống', 'invalid': 'Địa chỉ email không hợp lệ', 'max_length': 'Địa chỉ email không thể dài hơn 255 ký tự', 'null': 'Địa chỉ email không được bỏ trống', 'required': 'Địa chỉ email không được bỏ trống', 'unique': 'Địa chỉ email đã tồn tại trên hệ thống'}, max_length=255, null=True, verbose_name='Địa chỉ email')),
                ('date_of_birth', models.DateField(blank=True, error_messages={'invalid': 'Ngày sinh không hợp lệ', 'null': 'Ngày sinh không được bỏ trống', 'required': 'Ngày sinh không được bỏ trống'}, null=True, verbose_name='Ngày sinh')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Đang hoạt động'), ('NOT_ACTIVATED', 'Chưa kích hoạt'), ('LOCKED', 'Vô hiệu hóa')], default='ACTIVATED', error_messages={'blank': 'Trạng thái khách hàng không được bỏ trống', 'invalid': 'Trạng thái khách hàng không hợp lệ', 'null': 'Trạng thái khách hàng không được bỏ trống', 'required': 'Trạng thái khách hàng không được bỏ trống'}, max_length=100, verbose_name='Trạng thái khách hàng')),
            ],
            options={
                'verbose_name': 'Tài khoản khách hàng',
                'verbose_name_plural': 'Tài khoản khách hàng',
                'db_table': 'accounts_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_cu_code_622509_idx'), models.Index(fields=['full_name'], name='accounts_cu_full_na_2ae038_idx'), models.Index(fields=['created_at'], name='accounts_cu_created_242e5c_idx'), models.Index(fields=['phone_number'], name='accounts_cu_phone_n_b183a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), models.Q(('phone_number__isnull', True), _negated=True), models.Q(('phone_number__exact', ''), _negated=True)), fields=('phone_number',), name='unique_active_customer_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), models.Q(('code__isnull', True), _negated=True), models.Q(('code__exact', ''), _negated=True)), fields=('code',), name='unique_customer_code'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['code'], name='accounts_us_code_2c75a3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['full_name'], name='accounts_us_full_na_88336b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), models.Q(('phone_number__isnull', True), _negated=True), models.Q(('phone_number__exact', ''), _negated=True)), fields=('phone_number',), name='unique_active_user_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), models.Q(('code__isnull', True), _negated=True), models.Q(('code__exact', ''), _negated=True)), fields=('code',), name='unique_user_code'),
        ),
    ]
